precompile(Tuple{Type{Union{}}})
precompile(Tuple{typeof(StructTypes.construct),Type{Bool},Bool})
precompile(Tuple{typeof(Base.:(|)),Int16,Int16})
precompile(Tuple{typeof(Base.Broadcast.broadcastable),UInt8})
precompile(Tuple{typeof(Base.:(-)),Int128,Int128})
precompile(Tuple{typeof(Base.div),Int128,Int128})
precompile(Tuple{Type{UInt128},Float64})
precompile(Tuple{Type{NamedTuple{(:precision,),T} where T<:Tuple},Tuple{Int64}})
precompile(Tuple{typeof(Base.:(*)),UInt64,UInt64})
precompile(Tuple{typeof(Base.signed),UInt64})
precompile(Tuple{typeof(Base.haskey),NamedTuple{(),Tuple{}},Int64})
precompile(Tuple{typeof(StructTypes.serializationname),Tuple{},Int64})
precompile(Tuple{Type{NamedTuple{(:allow_inf,),T} where T<:Tuple},Tuple{Bool}})
precompile(Tuple{typeof(Base.haskey),NamedTuple{(:allow_inf,),Tuple{Bool}},Symbol})
precompile(Tuple{typeof(Base.:(|)),UInt64,UInt64})
precompile(Tuple{typeof(Base.:(!=)),UInt64,UInt64})
precompile(Tuple{typeof(Base.:(==)),UInt64,UInt64})
precompile(Tuple{typeof(Base.haskey),NamedTuple{(),Tuple{}},Symbol})
precompile(Tuple{Type{GeoJSON.CRS},Nothing,Nothing})
precompile(Tuple{typeof(Base.merge_names),Tuple{Vararg{Symbol}},Tuple{Vararg{Symbol}}})
precompile(Tuple{typeof(Base.sym_in),Symbol,Tuple{Vararg{Symbol}}})
precompile(Tuple{typeof(Base.tail),Tuple{Symbol,Symbol,Symbol,Symbol,Symbol,Symbol,Symbol,Symbol,Symbol}})
precompile(Tuple{typeof(Base.tail),Tuple{Symbol,Symbol,Symbol,Symbol,Symbol,Symbol,Symbol,Symbol}})
precompile(Tuple{typeof(Base.tail),Tuple{Symbol,Symbol,Symbol,Symbol,Symbol,Symbol,Symbol}})
precompile(Tuple{typeof(Base.tail),Tuple{Symbol,Symbol,Symbol,Symbol,Symbol,Symbol}})
precompile(Tuple{typeof(Base.tail),Tuple{Symbol,Symbol,Symbol,Symbol,Symbol}})
precompile(Tuple{typeof(Base.tail),Tuple{Symbol,Symbol,Symbol,Symbol}})
precompile(Tuple{typeof(JSON3.read),Array{UInt8,1},Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}}})
precompile(Tuple{typeof(Base.getindex),NamedTuple{(:Point, :MultiPoint, :LineString, :MultiLineString, :Polygon, :MultiPolygon, :GeometryCollection, :Feature, :FeatureCollection),Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType,DataType,DataType}},Symbol})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.FeatureCollection{2,Float32}}})
precompile(Tuple{typeof(StructTypes.symbolin),Tuple{Symbol,Symbol},Symbol})
precompile(Tuple{typeof(Base.Broadcast._getindex),Tuple{UInt8},Int64})
precompile(Tuple{typeof(Base.convert),Type{Type},Type})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.FeatureCollection{2,Float32}}})
precompile(Tuple{Type{StructTypes.StructType},Union})
precompile(Tuple{Type{NamedTuple{(:Point, :MultiPoint, :LineString, :MultiLineString, :Polygon, :MultiPolygon, :GeometryCollection),T} where T<:Tuple},Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType}})
precompile(Tuple{typeof(Base.getindex),NamedTuple{(:Point, :MultiPoint, :LineString, :MultiLineString, :Polygon, :MultiPolygon, :GeometryCollection),Tuple{DataType,DataType,DataType,DataType,DataType,DataType,DataType}},Symbol})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(Base.isvarargtype),Any})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Polygon{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Polygon{2,Float32}},Int64,Int64})
precompile(Tuple{typeof(Base.setproperty!),JSON3.StructClosure{Array{UInt8,1},NamedTuple{(),Tuple{}}},Symbol,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Nothing,GeoJSON.Polygon{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.MultiPolygon{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.MultiPolygon{2,Float32}},Int64,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Nothing,GeoJSON.MultiPolygon{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.FeatureCollection{2,Float32}},Nothing,Array{GeoJSON.Feature{2,Float32},1},Nothing,Nothing,Nothing})
precompile(Tuple{typeof(GeoJSON.missT),Type{String}})
precompile(Tuple{typeof(GeoJSON.missT),Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(GeoJSON.missT),Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.FeatureCollection{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.FeatureCollection{2,Float32}},Int64,Int64})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float32,GeoJSON.FeatureCollection{2,Float32}},Symbol})
precompile(Tuple{typeof(JSON3.read),String,Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.LineString{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.LineString{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.LineString{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.LineString{2,Float32}},Int64,Int64})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.LineString{2,Float32}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.GeometryCollection{2,Float32}}})
precompile(Tuple{Type{GeoJSON.GeometryCollection{2,Float32}},Nothing,Nothing})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.GeometryCollection{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(Base.push!),Array{GeoJSON.AbstractGeometry{2,Float32},1},GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(JSON3.getbyte),Base.CodeUnits{UInt8,String},Int64})
precompile(Tuple{typeof(Base.:(!=)),UInt8,UInt8})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.Point{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.Point{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Point{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Point{2,Float32}},Int64,Int64})
precompile(Tuple{typeof(Base.push!),Array{GeoJSON.AbstractGeometry{2,Float32},1},GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(Base.setproperty!),JSON3.StructClosure{Base.CodeUnits{UInt8,String},NamedTuple{(),Tuple{}}},Symbol,Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.GeometryCollection{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.GeometryCollection{2,Float32}},Int64,Int64})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.GeometryCollection{2,Float32}})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(JSON3.read),String,Type{GeoJSON.GeoJSONWrapper{3,Float32,X} where X<:GeoJSON.GeoJSONT{3,Float32}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.LineString{3,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.LineString{3,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.LineString{3,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.LineString{3,Float32}},Int64,Int64})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.LineString{3,Float32}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.Feature{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,Nothing},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,Nothing},Int64,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Nothing,Nothing,Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Feature{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Feature{2,Float32}},Int64,Int64})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.Feature{2,Float32}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.MultiPoint{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.MultiPoint{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.MultiPoint{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.MultiPoint{2,Float32}},Int64,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Int64,Nothing,GeoJSON.MultiPoint{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Int64,Nothing,Nothing,Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(JSON3.invalid),JSON3.Error,Base.CodeUnits{UInt8,String},Int64,Type})
precompile(Tuple{typeof(Base.Enums.namemap),Type{JSON3.Error}})
precompile(Tuple{typeof(Base.print),Base.GenericIOBuffer{Array{UInt8,1}},JSON3.Error})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.MultiLineString{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.MultiLineString{2,Float32}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.MultiLineString{2,Float32}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.MultiLineString{2,Float32}},Int64,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},String,Array{Float32,1},GeoJSON.MultiLineString{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},String,Nothing,GeoJSON.Point{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Nothing,GeoJSON.MultiLineString{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.FeatureCollection{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Union})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.CRS},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.CRS},Int64,Int64})
precompile(Tuple{Type{GeoJSON.FeatureCollection{2,Float32}},Array{Float32,1},Array{GeoJSON.Feature{2,Float32},1},GeoJSON.CRS,Nothing,Nothing})
precompile(Tuple{typeof(GeoJSON.missT),Type{Int64}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Array{Float32,1},GeoJSON.MultiPolygon{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},String,Nothing,GeoJSON.LineString{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(GeoJSON.missT),Type{GeoJSON.LineString{2,Float32}}})
precompile(Tuple{typeof(GeoJSON.missT),Type{GeoJSON.Point{2,Float32}}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},String,Nothing,Nothing,Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},String,Nothing,GeoJSON.Polygon{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(GeoJSON.missT),Type{Float64}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},String,Nothing,GeoJSON.GeometryCollection{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(GeoJSON.missT),Type{GeoJSON.GeometryCollection{2,Float32}}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Nothing,GeoJSON.Point{2,Float32},Base.Dict{Symbol,Any}})
precompile(Tuple{typeof(GeoJSON.read),Array{UInt8,1}})

precompile(Tuple{typeof(Base.getindex),GeoJSON.FeatureCollection{2,Float32},Int64})
precompile(Tuple{typeof(Base.:(!=)),Symbol})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(GeoJSON.typestring),Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(Base.iterate),Base.Set{Symbol}})
precompile(Tuple{typeof(Base.iterate),Base.Set{Symbol},Int64})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.Feature{2,Float32},Symbol})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.Polygon{2,Float32},Symbol})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},Array{Array{Tuple{Float32,Float32},1},1}})
precompile(Tuple{typeof(Base.isassigned),Array{Array{Tuple{Float32,Float32},1},1},Int64,Int64})
precompile(Tuple{typeof(Base.getindex),Array{Array{Tuple{Float32,Float32},1},1},Int64,Int64})
precompile(Tuple{typeof(Base.alignment),Base.IOContext{Base.TTY},Array{Tuple{Float32,Float32},1}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Array{Tuple{Float32,Float32},1}})
precompile(Tuple{typeof(Base.typeinfo_eltype),Type{Array{Tuple{Float32,Float32},1}}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},String,Array{Tuple{Float32,Float32},1}})
precompile(Tuple{typeof(Base.isassigned),Array{Tuple{Float32,Float32},1},Int64,Int64})
precompile(Tuple{typeof(Base.getindex),Array{Tuple{Float32,Float32},1},Int64,Int64})
precompile(Tuple{typeof(Base.alignment),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Tuple{Float32,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Tuple{Float32,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},String,Tuple{Float32,Float32}})
precompile(Tuple{typeof(Base.replace_in_print_matrix),Array{Tuple{Float32,Float32},1},Int64,Int64,String})
precompile(Tuple{typeof(Base.replace_in_print_matrix),Array{Array{Tuple{Float32,Float32},1},1},Int64,Int64,String})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.Polygon{2,Float32},1},GeoJSON.Polygon{2,Float32},Int64})
precompile(Tuple{typeof(Base.ndims),Array{GeoJSON.Polygon{2,Float32},1}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.Polygon{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{GeoJSON.AbstractGeometry{2,Float32}}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{GeoJSON.AbstractGeometry{2,Float32},1},Array{GeoJSON.Polygon{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},GeoJSON.MultiPolygon{2,Float32},Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.AbstractGeometry{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.AbstractGeometry{2,Float32},1},GeoJSON.MultiPolygon{2,Float32},Int64})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.AbstractGeometry{2,Float32},1},GeoJSON.Polygon{2,Float32},Int64})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},Array{GeoJSON.AbstractGeometry{2,Float32},1}})
precompile(Tuple{typeof(Base.isassigned),Array{GeoJSON.AbstractGeometry{2,Float32},1},Int64,Int64})
precompile(Tuple{typeof(Base.getindex),Array{GeoJSON.AbstractGeometry{2,Float32},1},Int64,Int64})
precompile(Tuple{typeof(Base.alignment),Base.IOContext{Base.TTY},GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(GeoJSON.typestring),Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(Base.alignment),Base.IOContext{Base.TTY},GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},String,GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(Base.replace_in_print_matrix),Array{GeoJSON.AbstractGeometry{2,Float32},1},Int64,Int64,String})
precompile(Tuple{typeof(Base.collect),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},Array{GeoJSON.Feature{2,Float32},1}})
precompile(Tuple{typeof(Base.isassigned),Array{GeoJSON.Feature{2,Float32},1},Int64,Int64})
precompile(Tuple{typeof(Base.getindex),Array{GeoJSON.Feature{2,Float32},1},Int64,Int64})
precompile(Tuple{typeof(Base.alignment),Base.IOContext{Base.TTY},GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},String,GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.replace_in_print_matrix),Array{GeoJSON.Feature{2,Float32},1},Int64,Int64,String})
precompile(Tuple{typeof(GI.coordinates),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.isnothing),GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(GI.coordinates),GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(Base._array_for),Type{Array{Array{Tuple{Float32,Float32},1},1}},Base.HasShape{1},Tuple{Base.OneTo{Int64}}})
precompile(Tuple{typeof(Base.ndims),Array{Array{Array{Tuple{Float32,Float32},1},1},1}})
precompile(Tuple{typeof(Base.isnothing),GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(GI.coordinates),GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(Base.setindex_widen_up_to),Array{Array{Array{Tuple{Float32,Float32},1},1},1},Array{Array{Array{Tuple{Float32,Float32},1},1},1},Int64})
precompile(Tuple{typeof(GI.coordinates),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(GI.ngeom),GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(GI.getgeom),GeoJSON.Polygon{2,Float32},Int64})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.LineString{2,Float32}}})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}},GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(GeoJSON.read),String})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Nothing,Nothing,GeoJSON.LineString{2,Float32},Nothing})
precompile(Tuple{typeof(Base.prettyprint_getunits),Int64,Int64,Int64})
precompile(Tuple{typeof(Base.Ryu.writefixed),Float64,Int64})
precompile(Tuple{Type{Int64},Float64})
precompile(Tuple{typeof(Base.:(==)),Float64,Int64})
precompile(Tuple{typeof(Base.print),Base.GenericIOBuffer{Array{UInt8,1}},Int64,String,Vararg{String}})
precompile(Tuple{Type{NamedTuple{(:Point, :MultiPoint, :LineString, :MultiLineString, :Polygon, :MultiPolygon, :GeometryCollection),T} where T<:Tuple},NTuple{7,DataType}})
precompile(Tuple{Type{NamedTuple{(:Feature, :FeatureCollection),T} where T<:Tuple},Tuple{DataType,DataType}})
precompile(Tuple{typeof(JSON3.read),Array{UInt8,1},Type{GeoJSON.GeoJSONWrapper{2,Float64,X} where X<:GeoJSON.GeoJSONT{2,Float64}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.FeatureCollection{2,Float64}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.FeatureCollection{2,Float64}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.Polygon{2,Float64}}})
precompile(Tuple{typeof(Base.fieldname),Type{Tuple{Float64,Float64}},Int64})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.Polygon{2,Float64}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Polygon{2,Float64}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.Polygon{2,Float64}},Int64,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float64}},String,Nothing,GeoJSON.Polygon{2,Float64},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.LineString{2,Float64}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.LineString{2,Float64}}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.LineString{2,Float64}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.LineString{2,Float64}},Int64,Int64})
precompile(Tuple{Type{GeoJSON.Feature{2,Float64}},String,Nothing,GeoJSON.LineString{2,Float64},Base.Dict{Symbol,Any}})
precompile(Tuple{Type{GeoJSON.FeatureCollection{2,Float64}},Nothing,Array{GeoJSON.Feature{2,Float64},1},Nothing,Nothing,Nothing})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.FeatureCollection{2,Float64}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{Int64,GeoJSON.FeatureCollection{2,Float64}},Int64,Int64})
precompile(Tuple{typeof(StructTypes.construct),Type,GeoJSON.FeatureCollection{2,Float64}})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float64,X} where X<:GeoJSON.GeoJSONT{2,Float64}},GeoJSON.FeatureCollection{2,Float64}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float64,GeoJSON.FeatureCollection{2,Float64}},Symbol})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},GeoJSON.FeatureCollection{2,Float64}})
precompile(Tuple{Type{NamedTuple{(:numbertype,),T} where T<:Tuple},Tuple{DataType}})
precompile(Tuple{typeof(JSON3.read),String,Type{GeoJSON.GeoJSONWrapper{2,Float64,X} where X<:GeoJSON.GeoJSONT{2,Float64}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.FeatureCollection{2,Float64}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.LineString{2,Float64}}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float64}},Nothing,Nothing,GeoJSON.LineString{2,Float64},Nothing})
precompile(Tuple{Type{NamedTuple{(:numbertype, :lazyfc),T} where T<:Tuple},Tuple{DataType,Bool}})
precompile(Tuple{typeof(JSON3.read),Array{UInt8,1},Type{GeoJSON.LazyFeatureCollection{2,Float64}}})
precompile(Tuple{Type{GeoJSON.LazyFeatureCollection{2,Float64}},Nothing,Array{GeoJSON.LazyFeature{2,Float64},1},Nothing})
precompile(Tuple{typeof(JSON3.read),Array{UInt8,1},Type{GeoJSON.LazyFeatureCollection{2,Float32}}})
precompile(Tuple{Type{GeoJSON.LazyFeatureCollection{2,Float32}},Nothing,Array{GeoJSON.LazyFeature{2,Float32},1},Nothing})
precompile(Tuple{typeof(Base.show),Base.IOContext{Base.TTY},Base.Multimedia.MIME{Symbol("text/plain")},GeoJSON.LazyFeatureCollection{2,Float32}})
precompile(Tuple{Type{NamedTuple{(:lazyfc,),T} where T<:Tuple},Tuple{Bool}})
precompile(Tuple{Type{NamedTuple{(:ndim, :lazyfc),T} where T<:Tuple},Tuple{Int64,Bool}})
precompile(Tuple{Type{NamedTuple{(:ndim,),T} where T<:Tuple},Tuple{Int64}})
precompile(Tuple{typeof(JSON3.read),Array{UInt8,1},Type{GeoJSON.GeoJSONWrapper{3,Float32,X} where X<:GeoJSON.GeoJSONT{3,Float32}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.FeatureCollection{3,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.FeatureCollection{3,Float32}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.Polygon{3,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.Polygon{3,Float32}}})
precompile(Tuple{typeof(JSON3.invalid),JSON3.Error,Array{UInt8,1},Int64,Type})
precompile(Tuple{typeof(Base.string),Module})
precompile(Tuple{typeof(JSON3.read),Array{UInt8,1},Type{GeoJSON.GeoJSONWrapper{4,Float32,X} where X<:GeoJSON.GeoJSONT{4,Float32}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.FeatureCollection{4,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.FeatureCollection{4,Float32}}})
precompile(Tuple{Type{StructTypes.StructType},Type{GeoJSON.Polygon{4,Float32}}})
precompile(Tuple{typeof(Base.fieldname),Type{NTuple{4,Float32}},Int64})
precompile(Tuple{typeof(JSON3.read),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,UInt8,Type{GeoJSON.Polygon{4,Float32}}})
precompile(Tuple{Type{NamedTuple{(:exception, :backtrace),T} where T<:Tuple},Tuple{ArgumentError,Array{Union{Ptr{Nothing},Base.InterpreterIP},1}}})
precompile(Tuple{typeof(Base.getproperty),NamedTuple{(:exception, :backtrace),Tuple{ArgumentError,Array{Union{Ptr{Nothing},Base.InterpreterIP},1}}},Symbol})
precompile(Tuple{Type{NamedTuple{(:exception, :backtrace),T} where T<:Tuple},Tuple{ArgumentError,Array{Base.StackTraces.StackFrame,1}}})
precompile(Tuple{typeof(Base.indexed_iterate),NamedTuple{(:exception, :backtrace),Tuple{ArgumentError,Array{Base.StackTraces.StackFrame,1}}},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),NamedTuple{(:exception, :backtrace),Tuple{ArgumentError,Array{Base.StackTraces.StackFrame,1}}},Int64,Int64})
# From testsuite
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}},GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float32,GeoJSON.Feature{2,Float32}},Symbol})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.MultiPoint{2,Float32}})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.MultiLineString{2,Float32}})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.Point{2,Float32}})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}},GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float32,GeoJSON.MultiPolygon{2,Float32}},Symbol})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}},GeoJSON.LineString{2,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float32,GeoJSON.LineString{2,Float32}},Symbol})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.LineString{2,Float32}})
precompile(Tuple{typeof(GeoJSON.bbox),GeoJSON.LineString{2,Float32}})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{3,Float32,X} where X<:GeoJSON.GeoJSONT{3,Float32}},GeoJSON.LineString{3,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{3,Float32,GeoJSON.LineString{3,Float32}},Symbol})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.LineString{3,Float32}})
precompile(Tuple{typeof(GeoJSON.bbox),GeoJSON.LineString{3,Float32}})
precompile(Tuple{typeof(Base.propertynames),GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(GeoJSON.typestring),Type{GeoJSON.Point{2,Float32}}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.Point{2,Float32},Symbol})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.propertynames),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(GeoJSON.geometry),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(GeoJSON.properties),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.iterate),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.vect),GeoJSON.Feature{2,Float32}})
precompile(Tuple{Type{NamedTuple{(:features,),T} where T<:Tuple},Tuple{Array{GeoJSON.Feature{2,Float32},1}}})
precompile(Tuple{typeof(GeoJSON.features),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.:(==)),Array{GeoJSON.Feature{2,Float32},1},Array{GeoJSON.Feature{2,Float32},1}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.Feature{2,Float32},GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.Point{2,Float32},GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(Base.propertynames),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Tables.columnnames),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.Broadcast.broadcasted),Function,GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Axes,F,Args} where {Args<:Tuple} where {F} where Axes},typeof(GeoJSON.geometry),Tuple{Array{GeoJSON.Feature{2,Float32},1}}})
precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(GeoJSON.geometry),Tuple{Array{GeoJSON.Feature{2,Float32},1}}}})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.geometry),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}}}},Type{GeoJSON.Point{2,Float32}}})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.Point{2,Float32},1},GeoJSON.Point{2,Float32},Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.Point{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.geometry),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.vect),GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(Base.:(==)),Array{GeoJSON.Point{2,Float32},1},Array{GeoJSON.Point{2,Float32},1}})
precompile(Tuple{typeof(Base.iterate),GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(Base.vect),GeoJSON.Feature{2,Float32},Vararg{GeoJSON.Feature{2,Float32}}})
precompile(Tuple{typeof(JSON3.read),StructTypes.AbstractType,Base.CodeUnits{UInt8,String},Int64,Int64,UInt8,Type{GeoJSON.AbstractGeometry{2,Float32}}})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}},GeoJSON.GeometryCollection{2,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float32,GeoJSON.GeometryCollection{2,Float32}},Symbol})
precompile(Tuple{Type{GeoJSON.GeoJSONWrapper{2,Float32,X} where X<:GeoJSON.GeoJSONT{2,Float32}},GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.GeoJSONWrapper{2,Float32,GeoJSON.Point{2,Float32}},Symbol})
precompile(Tuple{typeof(GeoJSON.write),GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.Feature{2,Float32}},Nothing})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.Feature{2,Float32}},Int64})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.MultiPoint{2,Float32},GeoJSON.MultiPoint{2,Float32}})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.Feature{2,Float32}},String})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.Feature{2,Float32}},Array{Float32,1}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.MultiLineString{2,Float32},GeoJSON.MultiLineString{2,Float32}})
precompile(Tuple{typeof(GeoJSON.write),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.FeatureCollection{2,Float32}},Array{Float32,1}})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.FeatureCollection{2,Float32}},GeoJSON.CRS})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(Base.foreach),Function,GeoJSON.FeatureCollection{2,Float32},GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.MultiPolygon{2,Float32},GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(StructTypes.isempty),Type{GeoJSON.FeatureCollection{2,Float32}},Nothing})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,Type{GeoJSON.LineString{2,Float32}}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.LineString{2,Float32},GeoJSON.LineString{2,Float32}})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,Type{GeoJSON.Point{2,Float32}}})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,Type{GeoJSON.Polygon{2,Float32}}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.Polygon{2,Float32},GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,GeoJSON.Polygon{2,Float32}})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,GeoJSON.Point{2,Float32}})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,Type{GeoJSON.GeometryCollection{2,Float32}}})
precompile(Tuple{typeof(Base.:(==)),GeoJSON.GeometryCollection{2,Float32},GeoJSON.GeometryCollection{2,Float32}})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.coordinates),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.AbstractGeometry{2,Float32},1},Tuple{Bool},Tuple{Int64}}}},Type{Array{Array{Tuple{Float32,Float32},1},1}}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Array{Array{Tuple{Float32,Float32},1},1},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.coordinates),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.AbstractGeometry{2,Float32},1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.coordinates),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.AbstractGeometry{2,Float32},1},Tuple{Bool},Tuple{Int64}}}},Type{Any}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Any,1},Array{Array{Array{Tuple{Float32,Float32},1},1},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.coordinates),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.AbstractGeometry{2,Float32},1},Tuple{Bool},Tuple{Int64}}}},Tuple{Float32,Float32},Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{Type{StructTypes.StructType},Type{Union{GeoJSON.MultiPolygon{2,Float32},GeoJSON.Polygon{2,Float32}}}})
precompile(Tuple{typeof(JSON3.write),StructTypes.AbstractType,Array{UInt8,1},Int64,Int64,Type{Union{GeoJSON.MultiPolygon{2,Float32},GeoJSON.Polygon{2,Float32}}}})
precompile(Tuple{typeof(JSON3.write),StructTypes.UnorderedStruct,Array{UInt8,1},Int64,Int64,Type{Union{Base.Missing,GeoJSON.Point{2,Float32}}}})
precompile(Tuple{typeof(Tables.istable),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Tables.rows),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Tables.columns),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.MultiPolygon{2,Float32},1},GeoJSON.MultiPolygon{2,Float32},Int64})
precompile(Tuple{typeof(Tables.rowtable),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Tables.columntable),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.first),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.iterate),GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{GeoJSON.Feature{2,Float32},Int64},Int64})
precompile(Tuple{typeof(Base.indexed_iterate),Tuple{GeoJSON.Feature{2,Float32},Int64},Int64,Int64})
precompile(Tuple{typeof(GeoJSON.coordinates),GeoJSON.MultiPolygon{2,Float32}})
precompile(Tuple{typeof(Base.show),Base.GenericIOBuffer{Array{UInt8,1}},Base.Multimedia.MIME{Symbol("text/plain")},GeoJSON.Feature{2,Float32}})
precompile(Tuple{typeof(GeoJSON.write),String,GeoJSON.FeatureCollection{2,Float32}})
precompile(Tuple{typeof(GeoJSON.typestring),Type{Nothing}})
precompile(Tuple{typeof(Base.getproperty),GeoJSON.FeatureCollection{2,Float32},Symbol})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{Base.Missing}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Base.Missing,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{Union{Base.Missing,GeoJSON.Point{2,Float32}}}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1},Array{Base.Missing,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},GeoJSON.Point{2,Float32},Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.getindex),Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1},Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{Int64}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Int64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{Union{Base.Missing,Int64}}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Union{Base.Missing,Int64},1},Array{Int64,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.Missing,Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Union{Base.Missing,Int64},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.setindex!),Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1},Base.Missing,Int64})
precompile(Tuple{typeof(Base.setindex!),Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1},GeoJSON.Point{2,Float32},Int64})
precompile(Tuple{Type{Tables.CopiedColumns{T} where T},NamedTuple{(:a, :b, :geometry),Tuple{Array{Union{Base.Missing,Int64},1},Array{Base.Missing,1},Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1}}}})
precompile(Tuple{typeof(Tables._eltypes),Type{NamedTuple{(:a, :b, :geometry),Tuple{Array{Union{Base.Missing,Int64},1},Array{Base.Missing,1},Array{Union{Base.Missing,GeoJSON.Point{2,Float32}},1}}}}})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{String}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{String,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Type{Union{Base.Missing,String}}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Union{Base.Missing,String},1},Array{String,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.Missing,Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{Union{Base.Missing,String},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{Union{Base.Missing,String},1},Array{Base.Missing,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(Base.getproperty),Tuple{Base.Broadcast.Extruded{Array{GeoJSON.Feature{2,Float32},1},Tuple{Bool},Tuple{Int64}},Base.RefValue{Symbol}}},String,Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{Type{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Axes,F,Args} where {Args<:Tuple} where {F} where Axes},typeof(GeoJSON.read),Tuple{Array{String,1}}})
precompile(Tuple{typeof(Base.Broadcast.materialize),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(GeoJSON.read),Tuple{Array{String,1}}}})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Type{GeoJSON.MultiPolygon{2,Float32}}})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.MultiPolygon{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Type{GeoJSON.AbstractGeometry{2,Float32}}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{GeoJSON.AbstractGeometry{2,Float32},1},Array{GeoJSON.MultiPolygon{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},GeoJSON.LineString{2,Float32},Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.AbstractGeometry{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Type{GeoJSON.AbstractGeometry{D,Float32} where D}})
precompile(Tuple{typeof(Base.Broadcast.restart_copyto_nonleaf!),Array{GeoJSON.AbstractGeometry{D,Float32} where D,1},Array{GeoJSON.AbstractGeometry{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},GeoJSON.LineString{3,Float32},Int64,Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.AbstractGeometry{D,Float32} where D,1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.all),Function,Array{GeoJSON.AbstractGeometry{D,Float32} where D,1}})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Type{GeoJSON.Feature{2,Float32}}})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.Feature{2,Float32},1},GeoJSON.Feature{2,Float32},Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.Feature{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.all),Function,Array{GeoJSON.Feature{2,Float32},1}})
precompile(Tuple{typeof(Base.similar),Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Type{GeoJSON.FeatureCollection{2,Float32}}})
precompile(Tuple{typeof(Base.setindex!),Array{GeoJSON.FeatureCollection{2,Float32},1},GeoJSON.FeatureCollection{2,Float32},Int64})
precompile(Tuple{typeof(Base.Broadcast.copyto_nonleaf!),Array{GeoJSON.FeatureCollection{2,Float32},1},Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},typeof(GeoJSON.read),Tuple{Base.Broadcast.Extruded{Array{String,1},Tuple{Bool},Tuple{Int64}}}},Base.OneTo{Int64},Int64,Int64})
precompile(Tuple{typeof(Base.all),Function,Array{GeoJSON.FeatureCollection{2,Float32},1}})
precompile(Tuple{Type{GeoFormatTypes.GeoJSON{T} where T},String})
precompile(Tuple{typeof(GeoJSON.read),GeoFormatTypes.GeoJSON{String}})
precompile(Tuple{Type{GeoFormatTypes.GeoJSON{T} where T},Base.Dict{String,Any}})
precompile(Tuple{typeof(GeoJSON.read),GeoFormatTypes.GeoJSON{Base.Dict{String,Any}}})
precompile(Tuple{typeof(Base.:(!=)),GeoJSON.Point{2,Int64},GeoJSON.Point{2,Int64}})
precompile(Tuple{typeof(Base.:(!=)),GeoJSON.LineString{2,Int64},GeoJSON.MultiPoint{2,Int64}})
precompile(Tuple{Type{GeoJSON.Feature{2,Float32}},Int64,Nothing,Nothing,Nothing})
